twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # the value is the service's id
        openingHours : '@App\Service\OpeningHourGenerator'

when@test:
    twig:
        strict_variables: true
