vich_uploader:
    db_driver: orm

    mappings:
       parrot:
           uri_prefix: /images/parrot
           upload_destination: '%kernel.project_dir%/public/images/parrot'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
